### ISSUE TITLE
Provide js files as well

### ISSUE THREAD

**Issue by ch-weiss** [didomi/redux-orm-angular#1]
First of all, thank you very much for the selectors. They are really helping a lot, not just as selectors but as a doc how to combine Redux-Orm with Angular in the right way.

I also appreciate very much that it is a TS version. The only thing I am missing is a distribution with js files so that it is not necessary to transpile files of a node package as well. Thank you for considering it!

**Comment by jawadst** [comment]
@ch-weiss 
Thanks for your message and sorry for the slow reply.

I have published a new version (2.0.0) that is a full JavaScript distribution (with typings) and that supports Angular Package Format (https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) for compatibility with Angular 5.

It should do what you want and does not require to be transpiled. Let me know if that works for you.
